### ISSUE TITLE
1.18.2 Axolotl and Turtle's vision is permanently zoomed, even if its in water

### ISSUE THREAD

**Issue by Inonedn** [Budschie/BudschieMorphMod#79]

**Comment by Budschie** [comment]
Yeah, I should really fix this as it is really annoying, especially when you are morphed as a turtle or as a spider.

**Comment by Budschie** [comment]
This issue has now been fixed with commit cd46f4bf8faf3e4c06187eebb5a586bfaa69bfe5.
I should note however that there is still some weird behaviour when you go in and out of webs really quickly as a cave spider.

**Comment by Budschie** [comment]
Alright, fixed the weird FOV behaviour when a cave spider is in a cobweb in this commit: bd7db2af7fab3bacfcd5ec4bab083b0b5f37536c. Finding this issue was actually surprisingly difficult (took me 1-2h or so), but now I think there shouldn't be any FOV issues anymore. If you however still encounter problems regarding the FOV in future releases, please contact me.
