### ISSUE TITLE
Friend dropped morph and got kicked out of server, and couldn't join back.

### ISSUE THREAD

**Issue by USSDXB** [Budschie/BudschieMorphMod#96]
So one of my friends dropped a morph and got kicked out of our aternos server and got an "Invalid Player Data" error, when he tried to rejoin.

**Comment by Budschie** [comment]
What version of this mod are you using?

**Comment by USSDXB** [comment]
We were using the latest version,

**Comment by TheM3ta** [comment]
Hey my friend had the same issue, he was dropping a blaze morph while morphed as a bat, he went into singleplayer and the same thing happened, when looking at the console on the server it said something like index issue so I don't know how you coded the mod but it might have to do something with that, anyway the fix is pretty simple I just had to spam the command to add the blaze morph to his morph list while he was trying to join and with the right timing it worked and he could join again, hope that helps in some way

**Comment by sansalife** [comment]
a bit of added information to this to help budschie out. what is going on is when someone is on the morph in the last of the array and they delete one above it -say they are on morph number 4 of 4 and delete number 2, it creates an out of bounds index and kicks the player since it does not update the player morphed number from 4 to 3. this can be fixed by editing the player data and setting them at a lower number or deleting them from the world. 

for those who have this issue, be sure you are not morphed when removing anything from your list just to be sure you are not on the last in the array :)

**Comment by Budschie** [comment]
This should be fixed in the newest version because the mod doesn't use indices anymore.
